"""ont metrics

Revision ID: 12bd6e078477
Revises: 
Create Date: 2022-05-05 20:03:07.356581

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12bd6e078477'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ont_metrics',
    sa.Column('mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=127), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_ont_metrics')),
    sa.UniqueConstraint('name', name=op.f('uq_ont_metrics_name'))
    )
    op.create_index(op.f('ix_ont_metrics_uuid'), 'ont_metrics', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ont_metrics_uuid'), table_name='ont_metrics')
    op.drop_table('ont_metrics')
    # ### end Alembic commands ###
