"""src docs

Revision ID: a5ee9c5abce5
Revises: 12bd6e078477
Create Date: 2022-06-06 02:05:04.189468

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a5ee9c5abce5'
down_revision = '12bd6e078477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('src_docs',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=127), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(length=127), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_src_docs')),
    sa.UniqueConstraint('link', name=op.f('uq_src_docs_link')),
    sa.UniqueConstraint('name', name=op.f('uq_src_docs_name'))
    )
    op.create_index(op.f('ix_src_docs_uuid'), 'src_docs', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_src_docs_uuid'), table_name='src_docs')
    op.drop_table('src_docs')
    # ### end Alembic commands ###
