"""doc documents

Revision ID: 8f2049326ae0
Revises: a5ee9c5abce5
Create Date: 2022-06-06 19:59:04.583786

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f2049326ae0'
down_revision = 'a5ee9c5abce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc_documents',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=127), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(length=2047), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('hash_value', sqlmodel.sql.sqltypes.AutoString(length=56), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_doc_documents')),
    sa.UniqueConstraint('link', name=op.f('uq_doc_documents_link'))
    )
    op.create_index(op.f('ix_doc_documents_hash_value'), 'doc_documents', ['hash_value'], unique=False)
    op.create_index(op.f('ix_doc_documents_uuid'), 'doc_documents', ['uuid'], unique=True)
    op.drop_index('ix_src_docs_uuid', table_name='src_docs')
    op.drop_table('src_docs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('src_docs',
    sa.Column('name', sa.VARCHAR(length=127), autoincrement=False, nullable=False),
    sa.Column('link', sa.VARCHAR(length=127), autoincrement=False, nullable=False),
    sa.Column('uuid', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('uuid', name='pk_src_docs'),
    sa.UniqueConstraint('link', name='uq_src_docs_link'),
    sa.UniqueConstraint('name', name='uq_src_docs_name')
    )
    op.create_index('ix_src_docs_uuid', 'src_docs', ['uuid'], unique=False)
    op.drop_index(op.f('ix_doc_documents_uuid'), table_name='doc_documents')
    op.drop_index(op.f('ix_doc_documents_hash_value'), table_name='doc_documents')
    op.drop_table('doc_documents')
    # ### end Alembic commands ###
