"""document index

Revision ID: 488f6eddc1ee
Revises: 8f2049326ae0
Create Date: 2022-06-08 20:23:04.680295

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = '488f6eddc1ee'
down_revision = '8f2049326ae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc_documents_index',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('metric_name', sqlmodel.sql.sqltypes.AutoString(length=127), nullable=False),
    sa.Column('sentence_number', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('document_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['doc_documents.uuid'], name=op.f('fk_doc_documents_index_document_id_doc_documents')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_doc_documents_index'))
    )
    op.create_index(op.f('ix_doc_documents_index_uuid'), 'doc_documents_index', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doc_documents_index_uuid'), table_name='doc_documents_index')
    op.drop_table('doc_documents_index')
    # ### end Alembic commands ###
