"""document fix

Revision ID: b106d4324f03
Revises: 488f6eddc1ee
Create Date: 2022-06-08 21:11:45.310104

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b106d4324f03'
down_revision = '488f6eddc1ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc_documents', sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doc_documents', 'file_path')
    # ### end Alembic commands ###
